if(isAndroid){
	instance_destroy(andrbutt_back);
	instance_destroy(andrbutt_enter);
	instance_destroy(andrbutt_left);
	instance_destroy(andrbutt_right);
	instance_destroy(andrbutt_up);
	instance_destroy(andrbutt_down);
	if(global.debug){
		instance_destroy(andrbutt_dbg);
		instance_destroy(andrbutt_dbgbound);
	}
}